package com.z.dao.mapper;

import com.z.pojo.UseRecord;

public interface UseRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    int insert(UseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    int insertSelective(UseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    UseRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    int updateByPrimaryKeySelective(UseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userecord
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    int updateByPrimaryKey(UseRecord record);
}