package com.z.dao.mapper;

import com.z.pojo.User;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Apr 12 14:27:01 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Apr 12 14:27:01 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Apr 12 14:27:01 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Apr 12 14:27:01 CST 2018
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Apr 12 14:27:01 CST 2018
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Apr 12 14:27:01 CST 2018
     */
    int updateByPrimaryKey(User record);

    User userLogin(@Param("username") String username, @Param("password") String password);

    float retrieveUserBalance(@Param("userId") int userId);

    void setUserImage(@Param("userId") int userId,@Param("url") String url);

    String getUserImage(@Param("userId")int userId);

    int changeUserBalance(@Param("userId")int userId,@Param("newBalance") double newBalance);
}