package com.z.dao.mapper;

import com.z.pojo.Xia;

public interface XiaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xia
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xia
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    int insert(Xia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xia
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    int insertSelective(Xia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xia
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    Xia selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xia
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    int updateByPrimaryKeySelective(Xia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xia
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    int updateByPrimaryKey(Xia record);
}