package com.z.pojo;

public class UseRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userecord.id
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userecord.startSite
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    private String startsite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userecord.stopSite
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    private String stopsite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userecord.startTime
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    private String starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userecord.stopTime
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    private String stoptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userecord.duration
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    private String duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userecord.price
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userecord.totalMoney
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    private Double totalmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userecord.u_id
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userecord.x_id
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    private Integer xId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userecord.state
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userecord.id
     *
     * @return the value of userecord.id
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userecord.id
     *
     * @param id the value for userecord.id
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userecord.startSite
     *
     * @return the value of userecord.startSite
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public String getStartsite() {
        return startsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userecord.startSite
     *
     * @param startsite the value for userecord.startSite
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public void setStartsite(String startsite) {
        this.startsite = startsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userecord.stopSite
     *
     * @return the value of userecord.stopSite
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public String getStopsite() {
        return stopsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userecord.stopSite
     *
     * @param stopsite the value for userecord.stopSite
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public void setStopsite(String stopsite) {
        this.stopsite = stopsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userecord.startTime
     *
     * @return the value of userecord.startTime
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userecord.startTime
     *
     * @param starttime the value for userecord.startTime
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userecord.stopTime
     *
     * @return the value of userecord.stopTime
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public String getStoptime() {
        return stoptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userecord.stopTime
     *
     * @param stoptime the value for userecord.stopTime
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public void setStoptime(String stoptime) {
        this.stoptime = stoptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userecord.duration
     *
     * @return the value of userecord.duration
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userecord.duration
     *
     * @param duration the value for userecord.duration
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public void setDuration(String duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userecord.price
     *
     * @return the value of userecord.price
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userecord.price
     *
     * @param price the value for userecord.price
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userecord.totalMoney
     *
     * @return the value of userecord.totalMoney
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public Double getTotalmoney() {
        return totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userecord.totalMoney
     *
     * @param totalmoney the value for userecord.totalMoney
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public void setTotalmoney(Double totalmoney) {
        this.totalmoney = totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userecord.u_id
     *
     * @return the value of userecord.u_id
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userecord.u_id
     *
     * @param uId the value for userecord.u_id
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userecord.x_id
     *
     * @return the value of userecord.x_id
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public Integer getxId() {
        return xId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userecord.x_id
     *
     * @param xId the value for userecord.x_id
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public void setxId(Integer xId) {
        this.xId = xId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userecord.state
     *
     * @return the value of userecord.state
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userecord.state
     *
     * @param state the value for userecord.state
     *
     * @mbggenerated Wed Apr 04 10:43:47 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    @Override
    public String toString() {
        return "UseRecord{" +
                "id=" + id +
                ", startsite='" + startsite + '\'' +
                ", stopsite='" + stopsite + '\'' +
                ", starttime='" + starttime + '\'' +
                ", stoptime='" + stoptime + '\'' +
                ", duration='" + duration + '\'' +
                ", price=" + price +
                ", totalmoney=" + totalmoney +
                ", uId=" + uId +
                ", xId=" + xId +
                ", state=" + state +
                '}';
    }
}