package com.z.pojo;

public class Xia {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xia.id
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xia.latitude
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xia.longitude
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xia.price
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xia.type
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xia.state
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xia.id
     *
     * @return the value of xia.id
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xia.id
     *
     * @param id the value for xia.id
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xia.latitude
     *
     * @return the value of xia.latitude
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xia.latitude
     *
     * @param latitude the value for xia.latitude
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xia.longitude
     *
     * @return the value of xia.longitude
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xia.longitude
     *
     * @param longitude the value for xia.longitude
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xia.price
     *
     * @return the value of xia.price
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xia.price
     *
     * @param price the value for xia.price
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xia.type
     *
     * @return the value of xia.type
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xia.type
     *
     * @param type the value for xia.type
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xia.state
     *
     * @return the value of xia.state
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xia.state
     *
     * @param state the value for xia.state
     *
     * @mbggenerated Tue Feb 06 14:54:22 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }
}